---
- name: Deploy Flask Docker App
  hosts: web
  become: yes

  tasks:
    - name: Run Flask container from local image
      docker_container:
        name: flaskapp
        image: flaskapp:latest
        state: started
        restart_policy: always
        published_ports:
          - "80:5000"
